version: '3.8'

services:
  vectron:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/vectron/data
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - EMBEDDING_SERVICE_URL=http://embedding-service:8000
    depends_on:
      - embedding-service

  embedding-service:
    build:
      context: ./python/embedding_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PORT=8000
    volumes:
      - ./python/embedding_service:/app 